# handler
.text

.globl c0re_alltraps

vector0:
    pushl $0
    pushl $0
    jmp c0re_alltraps

vector1:
    pushl $0
    pushl $1
    jmp c0re_alltraps

vector2:
    pushl $0
    pushl $2
    jmp c0re_alltraps

vector3:
    pushl $0
    pushl $3
    jmp c0re_alltraps

vector4:
    pushl $0
    pushl $4
    jmp c0re_alltraps

vector5:
    pushl $0
    pushl $5
    jmp c0re_alltraps

vector6:
    pushl $0
    pushl $6
    jmp c0re_alltraps

vector7:
    pushl $0
    pushl $7
    jmp c0re_alltraps

vector8:
    pushl $8
    jmp c0re_alltraps

vector9:
    pushl $9
    jmp c0re_alltraps

vector10:
    pushl $10
    jmp c0re_alltraps

vector11:
    pushl $11
    jmp c0re_alltraps

vector12:
    pushl $12
    jmp c0re_alltraps

vector13:
    pushl $13
    jmp c0re_alltraps

vector14:
    pushl $14
    jmp c0re_alltraps

vector15:
    pushl $0
    pushl $15
    jmp c0re_alltraps

vector16:
    pushl $0
    pushl $16
    jmp c0re_alltraps

vector17:
    pushl $17
    jmp c0re_alltraps

vector18:
    pushl $0
    pushl $18
    jmp c0re_alltraps

vector19:
    pushl $0
    pushl $19
    jmp c0re_alltraps

vector20:
    pushl $0
    pushl $20
    jmp c0re_alltraps

vector21:
    pushl $0
    pushl $21
    jmp c0re_alltraps

vector22:
    pushl $0
    pushl $22
    jmp c0re_alltraps

vector23:
    pushl $0
    pushl $23
    jmp c0re_alltraps

vector24:
    pushl $0
    pushl $24
    jmp c0re_alltraps

vector25:
    pushl $0
    pushl $25
    jmp c0re_alltraps

vector26:
    pushl $0
    pushl $26
    jmp c0re_alltraps

vector27:
    pushl $0
    pushl $27
    jmp c0re_alltraps

vector28:
    pushl $0
    pushl $28
    jmp c0re_alltraps

vector29:
    pushl $0
    pushl $29
    jmp c0re_alltraps

vector30:
    pushl $0
    pushl $30
    jmp c0re_alltraps

vector31:
    pushl $0
    pushl $31
    jmp c0re_alltraps

vector32:
    pushl $0
    pushl $32
    jmp c0re_alltraps

vector33:
    pushl $0
    pushl $33
    jmp c0re_alltraps

vector34:
    pushl $0
    pushl $34
    jmp c0re_alltraps

vector35:
    pushl $0
    pushl $35
    jmp c0re_alltraps

vector36:
    pushl $0
    pushl $36
    jmp c0re_alltraps

vector37:
    pushl $0
    pushl $37
    jmp c0re_alltraps

vector38:
    pushl $0
    pushl $38
    jmp c0re_alltraps

vector39:
    pushl $0
    pushl $39
    jmp c0re_alltraps

vector40:
    pushl $0
    pushl $40
    jmp c0re_alltraps

vector41:
    pushl $0
    pushl $41
    jmp c0re_alltraps

vector42:
    pushl $0
    pushl $42
    jmp c0re_alltraps

vector43:
    pushl $0
    pushl $43
    jmp c0re_alltraps

vector44:
    pushl $0
    pushl $44
    jmp c0re_alltraps

vector45:
    pushl $0
    pushl $45
    jmp c0re_alltraps

vector46:
    pushl $0
    pushl $46
    jmp c0re_alltraps

vector47:
    pushl $0
    pushl $47
    jmp c0re_alltraps

vector48:
    pushl $0
    pushl $48
    jmp c0re_alltraps

vector49:
    pushl $0
    pushl $49
    jmp c0re_alltraps

vector50:
    pushl $0
    pushl $50
    jmp c0re_alltraps

vector51:
    pushl $0
    pushl $51
    jmp c0re_alltraps

vector52:
    pushl $0
    pushl $52
    jmp c0re_alltraps

vector53:
    pushl $0
    pushl $53
    jmp c0re_alltraps

vector54:
    pushl $0
    pushl $54
    jmp c0re_alltraps

vector55:
    pushl $0
    pushl $55
    jmp c0re_alltraps

vector56:
    pushl $0
    pushl $56
    jmp c0re_alltraps

vector57:
    pushl $0
    pushl $57
    jmp c0re_alltraps

vector58:
    pushl $0
    pushl $58
    jmp c0re_alltraps

vector59:
    pushl $0
    pushl $59
    jmp c0re_alltraps

vector60:
    pushl $0
    pushl $60
    jmp c0re_alltraps

vector61:
    pushl $0
    pushl $61
    jmp c0re_alltraps

vector62:
    pushl $0
    pushl $62
    jmp c0re_alltraps

vector63:
    pushl $0
    pushl $63
    jmp c0re_alltraps

vector64:
    pushl $0
    pushl $64
    jmp c0re_alltraps

vector65:
    pushl $0
    pushl $65
    jmp c0re_alltraps

vector66:
    pushl $0
    pushl $66
    jmp c0re_alltraps

vector67:
    pushl $0
    pushl $67
    jmp c0re_alltraps

vector68:
    pushl $0
    pushl $68
    jmp c0re_alltraps

vector69:
    pushl $0
    pushl $69
    jmp c0re_alltraps

vector70:
    pushl $0
    pushl $70
    jmp c0re_alltraps

vector71:
    pushl $0
    pushl $71
    jmp c0re_alltraps

vector72:
    pushl $0
    pushl $72
    jmp c0re_alltraps

vector73:
    pushl $0
    pushl $73
    jmp c0re_alltraps

vector74:
    pushl $0
    pushl $74
    jmp c0re_alltraps

vector75:
    pushl $0
    pushl $75
    jmp c0re_alltraps

vector76:
    pushl $0
    pushl $76
    jmp c0re_alltraps

vector77:
    pushl $0
    pushl $77
    jmp c0re_alltraps

vector78:
    pushl $0
    pushl $78
    jmp c0re_alltraps

vector79:
    pushl $0
    pushl $79
    jmp c0re_alltraps

vector80:
    pushl $0
    pushl $80
    jmp c0re_alltraps

vector81:
    pushl $0
    pushl $81
    jmp c0re_alltraps

vector82:
    pushl $0
    pushl $82
    jmp c0re_alltraps

vector83:
    pushl $0
    pushl $83
    jmp c0re_alltraps

vector84:
    pushl $0
    pushl $84
    jmp c0re_alltraps

vector85:
    pushl $0
    pushl $85
    jmp c0re_alltraps

vector86:
    pushl $0
    pushl $86
    jmp c0re_alltraps

vector87:
    pushl $0
    pushl $87
    jmp c0re_alltraps

vector88:
    pushl $0
    pushl $88
    jmp c0re_alltraps

vector89:
    pushl $0
    pushl $89
    jmp c0re_alltraps

vector90:
    pushl $0
    pushl $90
    jmp c0re_alltraps

vector91:
    pushl $0
    pushl $91
    jmp c0re_alltraps

vector92:
    pushl $0
    pushl $92
    jmp c0re_alltraps

vector93:
    pushl $0
    pushl $93
    jmp c0re_alltraps

vector94:
    pushl $0
    pushl $94
    jmp c0re_alltraps

vector95:
    pushl $0
    pushl $95
    jmp c0re_alltraps

vector96:
    pushl $0
    pushl $96
    jmp c0re_alltraps

vector97:
    pushl $0
    pushl $97
    jmp c0re_alltraps

vector98:
    pushl $0
    pushl $98
    jmp c0re_alltraps

vector99:
    pushl $0
    pushl $99
    jmp c0re_alltraps

vector100:
    pushl $0
    pushl $100
    jmp c0re_alltraps

vector101:
    pushl $0
    pushl $101
    jmp c0re_alltraps

vector102:
    pushl $0
    pushl $102
    jmp c0re_alltraps

vector103:
    pushl $0
    pushl $103
    jmp c0re_alltraps

vector104:
    pushl $0
    pushl $104
    jmp c0re_alltraps

vector105:
    pushl $0
    pushl $105
    jmp c0re_alltraps

vector106:
    pushl $0
    pushl $106
    jmp c0re_alltraps

vector107:
    pushl $0
    pushl $107
    jmp c0re_alltraps

vector108:
    pushl $0
    pushl $108
    jmp c0re_alltraps

vector109:
    pushl $0
    pushl $109
    jmp c0re_alltraps

vector110:
    pushl $0
    pushl $110
    jmp c0re_alltraps

vector111:
    pushl $0
    pushl $111
    jmp c0re_alltraps

vector112:
    pushl $0
    pushl $112
    jmp c0re_alltraps

vector113:
    pushl $0
    pushl $113
    jmp c0re_alltraps

vector114:
    pushl $0
    pushl $114
    jmp c0re_alltraps

vector115:
    pushl $0
    pushl $115
    jmp c0re_alltraps

vector116:
    pushl $0
    pushl $116
    jmp c0re_alltraps

vector117:
    pushl $0
    pushl $117
    jmp c0re_alltraps

vector118:
    pushl $0
    pushl $118
    jmp c0re_alltraps

vector119:
    pushl $0
    pushl $119
    jmp c0re_alltraps

vector120:
    pushl $0
    pushl $120
    jmp c0re_alltraps

vector121:
    pushl $0
    pushl $121
    jmp c0re_alltraps

vector122:
    pushl $0
    pushl $122
    jmp c0re_alltraps

vector123:
    pushl $0
    pushl $123
    jmp c0re_alltraps

vector124:
    pushl $0
    pushl $124
    jmp c0re_alltraps

vector125:
    pushl $0
    pushl $125
    jmp c0re_alltraps

vector126:
    pushl $0
    pushl $126
    jmp c0re_alltraps

vector127:
    pushl $0
    pushl $127
    jmp c0re_alltraps

vector128:
    pushl $0
    pushl $128
    jmp c0re_alltraps

vector129:
    pushl $0
    pushl $129
    jmp c0re_alltraps

vector130:
    pushl $0
    pushl $130
    jmp c0re_alltraps

vector131:
    pushl $0
    pushl $131
    jmp c0re_alltraps

vector132:
    pushl $0
    pushl $132
    jmp c0re_alltraps

vector133:
    pushl $0
    pushl $133
    jmp c0re_alltraps

vector134:
    pushl $0
    pushl $134
    jmp c0re_alltraps

vector135:
    pushl $0
    pushl $135
    jmp c0re_alltraps

vector136:
    pushl $0
    pushl $136
    jmp c0re_alltraps

vector137:
    pushl $0
    pushl $137
    jmp c0re_alltraps

vector138:
    pushl $0
    pushl $138
    jmp c0re_alltraps

vector139:
    pushl $0
    pushl $139
    jmp c0re_alltraps

vector140:
    pushl $0
    pushl $140
    jmp c0re_alltraps

vector141:
    pushl $0
    pushl $141
    jmp c0re_alltraps

vector142:
    pushl $0
    pushl $142
    jmp c0re_alltraps

vector143:
    pushl $0
    pushl $143
    jmp c0re_alltraps

vector144:
    pushl $0
    pushl $144
    jmp c0re_alltraps

vector145:
    pushl $0
    pushl $145
    jmp c0re_alltraps

vector146:
    pushl $0
    pushl $146
    jmp c0re_alltraps

vector147:
    pushl $0
    pushl $147
    jmp c0re_alltraps

vector148:
    pushl $0
    pushl $148
    jmp c0re_alltraps

vector149:
    pushl $0
    pushl $149
    jmp c0re_alltraps

vector150:
    pushl $0
    pushl $150
    jmp c0re_alltraps

vector151:
    pushl $0
    pushl $151
    jmp c0re_alltraps

vector152:
    pushl $0
    pushl $152
    jmp c0re_alltraps

vector153:
    pushl $0
    pushl $153
    jmp c0re_alltraps

vector154:
    pushl $0
    pushl $154
    jmp c0re_alltraps

vector155:
    pushl $0
    pushl $155
    jmp c0re_alltraps

vector156:
    pushl $0
    pushl $156
    jmp c0re_alltraps

vector157:
    pushl $0
    pushl $157
    jmp c0re_alltraps

vector158:
    pushl $0
    pushl $158
    jmp c0re_alltraps

vector159:
    pushl $0
    pushl $159
    jmp c0re_alltraps

vector160:
    pushl $0
    pushl $160
    jmp c0re_alltraps

vector161:
    pushl $0
    pushl $161
    jmp c0re_alltraps

vector162:
    pushl $0
    pushl $162
    jmp c0re_alltraps

vector163:
    pushl $0
    pushl $163
    jmp c0re_alltraps

vector164:
    pushl $0
    pushl $164
    jmp c0re_alltraps

vector165:
    pushl $0
    pushl $165
    jmp c0re_alltraps

vector166:
    pushl $0
    pushl $166
    jmp c0re_alltraps

vector167:
    pushl $0
    pushl $167
    jmp c0re_alltraps

vector168:
    pushl $0
    pushl $168
    jmp c0re_alltraps

vector169:
    pushl $0
    pushl $169
    jmp c0re_alltraps

vector170:
    pushl $0
    pushl $170
    jmp c0re_alltraps

vector171:
    pushl $0
    pushl $171
    jmp c0re_alltraps

vector172:
    pushl $0
    pushl $172
    jmp c0re_alltraps

vector173:
    pushl $0
    pushl $173
    jmp c0re_alltraps

vector174:
    pushl $0
    pushl $174
    jmp c0re_alltraps

vector175:
    pushl $0
    pushl $175
    jmp c0re_alltraps

vector176:
    pushl $0
    pushl $176
    jmp c0re_alltraps

vector177:
    pushl $0
    pushl $177
    jmp c0re_alltraps

vector178:
    pushl $0
    pushl $178
    jmp c0re_alltraps

vector179:
    pushl $0
    pushl $179
    jmp c0re_alltraps

vector180:
    pushl $0
    pushl $180
    jmp c0re_alltraps

vector181:
    pushl $0
    pushl $181
    jmp c0re_alltraps

vector182:
    pushl $0
    pushl $182
    jmp c0re_alltraps

vector183:
    pushl $0
    pushl $183
    jmp c0re_alltraps

vector184:
    pushl $0
    pushl $184
    jmp c0re_alltraps

vector185:
    pushl $0
    pushl $185
    jmp c0re_alltraps

vector186:
    pushl $0
    pushl $186
    jmp c0re_alltraps

vector187:
    pushl $0
    pushl $187
    jmp c0re_alltraps

vector188:
    pushl $0
    pushl $188
    jmp c0re_alltraps

vector189:
    pushl $0
    pushl $189
    jmp c0re_alltraps

vector190:
    pushl $0
    pushl $190
    jmp c0re_alltraps

vector191:
    pushl $0
    pushl $191
    jmp c0re_alltraps

vector192:
    pushl $0
    pushl $192
    jmp c0re_alltraps

vector193:
    pushl $0
    pushl $193
    jmp c0re_alltraps

vector194:
    pushl $0
    pushl $194
    jmp c0re_alltraps

vector195:
    pushl $0
    pushl $195
    jmp c0re_alltraps

vector196:
    pushl $0
    pushl $196
    jmp c0re_alltraps

vector197:
    pushl $0
    pushl $197
    jmp c0re_alltraps

vector198:
    pushl $0
    pushl $198
    jmp c0re_alltraps

vector199:
    pushl $0
    pushl $199
    jmp c0re_alltraps

vector200:
    pushl $0
    pushl $200
    jmp c0re_alltraps

vector201:
    pushl $0
    pushl $201
    jmp c0re_alltraps

vector202:
    pushl $0
    pushl $202
    jmp c0re_alltraps

vector203:
    pushl $0
    pushl $203
    jmp c0re_alltraps

vector204:
    pushl $0
    pushl $204
    jmp c0re_alltraps

vector205:
    pushl $0
    pushl $205
    jmp c0re_alltraps

vector206:
    pushl $0
    pushl $206
    jmp c0re_alltraps

vector207:
    pushl $0
    pushl $207
    jmp c0re_alltraps

vector208:
    pushl $0
    pushl $208
    jmp c0re_alltraps

vector209:
    pushl $0
    pushl $209
    jmp c0re_alltraps

vector210:
    pushl $0
    pushl $210
    jmp c0re_alltraps

vector211:
    pushl $0
    pushl $211
    jmp c0re_alltraps

vector212:
    pushl $0
    pushl $212
    jmp c0re_alltraps

vector213:
    pushl $0
    pushl $213
    jmp c0re_alltraps

vector214:
    pushl $0
    pushl $214
    jmp c0re_alltraps

vector215:
    pushl $0
    pushl $215
    jmp c0re_alltraps

vector216:
    pushl $0
    pushl $216
    jmp c0re_alltraps

vector217:
    pushl $0
    pushl $217
    jmp c0re_alltraps

vector218:
    pushl $0
    pushl $218
    jmp c0re_alltraps

vector219:
    pushl $0
    pushl $219
    jmp c0re_alltraps

vector220:
    pushl $0
    pushl $220
    jmp c0re_alltraps

vector221:
    pushl $0
    pushl $221
    jmp c0re_alltraps

vector222:
    pushl $0
    pushl $222
    jmp c0re_alltraps

vector223:
    pushl $0
    pushl $223
    jmp c0re_alltraps

vector224:
    pushl $0
    pushl $224
    jmp c0re_alltraps

vector225:
    pushl $0
    pushl $225
    jmp c0re_alltraps

vector226:
    pushl $0
    pushl $226
    jmp c0re_alltraps

vector227:
    pushl $0
    pushl $227
    jmp c0re_alltraps

vector228:
    pushl $0
    pushl $228
    jmp c0re_alltraps

vector229:
    pushl $0
    pushl $229
    jmp c0re_alltraps

vector230:
    pushl $0
    pushl $230
    jmp c0re_alltraps

vector231:
    pushl $0
    pushl $231
    jmp c0re_alltraps

vector232:
    pushl $0
    pushl $232
    jmp c0re_alltraps

vector233:
    pushl $0
    pushl $233
    jmp c0re_alltraps

vector234:
    pushl $0
    pushl $234
    jmp c0re_alltraps

vector235:
    pushl $0
    pushl $235
    jmp c0re_alltraps

vector236:
    pushl $0
    pushl $236
    jmp c0re_alltraps

vector237:
    pushl $0
    pushl $237
    jmp c0re_alltraps

vector238:
    pushl $0
    pushl $238
    jmp c0re_alltraps

vector239:
    pushl $0
    pushl $239
    jmp c0re_alltraps

vector240:
    pushl $0
    pushl $240
    jmp c0re_alltraps

vector241:
    pushl $0
    pushl $241
    jmp c0re_alltraps

vector242:
    pushl $0
    pushl $242
    jmp c0re_alltraps

vector243:
    pushl $0
    pushl $243
    jmp c0re_alltraps

vector244:
    pushl $0
    pushl $244
    jmp c0re_alltraps

vector245:
    pushl $0
    pushl $245
    jmp c0re_alltraps

vector246:
    pushl $0
    pushl $246
    jmp c0re_alltraps

vector247:
    pushl $0
    pushl $247
    jmp c0re_alltraps

vector248:
    pushl $0
    pushl $248
    jmp c0re_alltraps

vector249:
    pushl $0
    pushl $249
    jmp c0re_alltraps

vector250:
    pushl $0
    pushl $250
    jmp c0re_alltraps

vector251:
    pushl $0
    pushl $251
    jmp c0re_alltraps

vector252:
    pushl $0
    pushl $252
    jmp c0re_alltraps

vector253:
    pushl $0
    pushl $253
    jmp c0re_alltraps

vector254:
    pushl $0
    pushl $254
    jmp c0re_alltraps

vector255:
    pushl $0
    pushl $255
    jmp c0re_alltraps

# vector table
.data
.globl c0re_trapvec
c0re_trapvec:
    .long vector0
    .long vector1
    .long vector2
    .long vector3
    .long vector4
    .long vector5
    .long vector6
    .long vector7
    .long vector8
    .long vector9
    .long vector10
    .long vector11
    .long vector12
    .long vector13
    .long vector14
    .long vector15
    .long vector16
    .long vector17
    .long vector18
    .long vector19
    .long vector20
    .long vector21
    .long vector22
    .long vector23
    .long vector24
    .long vector25
    .long vector26
    .long vector27
    .long vector28
    .long vector29
    .long vector30
    .long vector31
    .long vector32
    .long vector33
    .long vector34
    .long vector35
    .long vector36
    .long vector37
    .long vector38
    .long vector39
    .long vector40
    .long vector41
    .long vector42
    .long vector43
    .long vector44
    .long vector45
    .long vector46
    .long vector47
    .long vector48
    .long vector49
    .long vector50
    .long vector51
    .long vector52
    .long vector53
    .long vector54
    .long vector55
    .long vector56
    .long vector57
    .long vector58
    .long vector59
    .long vector60
    .long vector61
    .long vector62
    .long vector63
    .long vector64
    .long vector65
    .long vector66
    .long vector67
    .long vector68
    .long vector69
    .long vector70
    .long vector71
    .long vector72
    .long vector73
    .long vector74
    .long vector75
    .long vector76
    .long vector77
    .long vector78
    .long vector79
    .long vector80
    .long vector81
    .long vector82
    .long vector83
    .long vector84
    .long vector85
    .long vector86
    .long vector87
    .long vector88
    .long vector89
    .long vector90
    .long vector91
    .long vector92
    .long vector93
    .long vector94
    .long vector95
    .long vector96
    .long vector97
    .long vector98
    .long vector99
    .long vector100
    .long vector101
    .long vector102
    .long vector103
    .long vector104
    .long vector105
    .long vector106
    .long vector107
    .long vector108
    .long vector109
    .long vector110
    .long vector111
    .long vector112
    .long vector113
    .long vector114
    .long vector115
    .long vector116
    .long vector117
    .long vector118
    .long vector119
    .long vector120
    .long vector121
    .long vector122
    .long vector123
    .long vector124
    .long vector125
    .long vector126
    .long vector127
    .long vector128
    .long vector129
    .long vector130
    .long vector131
    .long vector132
    .long vector133
    .long vector134
    .long vector135
    .long vector136
    .long vector137
    .long vector138
    .long vector139
    .long vector140
    .long vector141
    .long vector142
    .long vector143
    .long vector144
    .long vector145
    .long vector146
    .long vector147
    .long vector148
    .long vector149
    .long vector150
    .long vector151
    .long vector152
    .long vector153
    .long vector154
    .long vector155
    .long vector156
    .long vector157
    .long vector158
    .long vector159
    .long vector160
    .long vector161
    .long vector162
    .long vector163
    .long vector164
    .long vector165
    .long vector166
    .long vector167
    .long vector168
    .long vector169
    .long vector170
    .long vector171
    .long vector172
    .long vector173
    .long vector174
    .long vector175
    .long vector176
    .long vector177
    .long vector178
    .long vector179
    .long vector180
    .long vector181
    .long vector182
    .long vector183
    .long vector184
    .long vector185
    .long vector186
    .long vector187
    .long vector188
    .long vector189
    .long vector190
    .long vector191
    .long vector192
    .long vector193
    .long vector194
    .long vector195
    .long vector196
    .long vector197
    .long vector198
    .long vector199
    .long vector200
    .long vector201
    .long vector202
    .long vector203
    .long vector204
    .long vector205
    .long vector206
    .long vector207
    .long vector208
    .long vector209
    .long vector210
    .long vector211
    .long vector212
    .long vector213
    .long vector214
    .long vector215
    .long vector216
    .long vector217
    .long vector218
    .long vector219
    .long vector220
    .long vector221
    .long vector222
    .long vector223
    .long vector224
    .long vector225
    .long vector226
    .long vector227
    .long vector228
    .long vector229
    .long vector230
    .long vector231
    .long vector232
    .long vector233
    .long vector234
    .long vector235
    .long vector236
    .long vector237
    .long vector238
    .long vector239
    .long vector240
    .long vector241
    .long vector242
    .long vector243
    .long vector244
    .long vector245
    .long vector246
    .long vector247
    .long vector248
    .long vector249
    .long vector250
    .long vector251
    .long vector252
    .long vector253
    .long vector254
    .long vector255
